api_platform:
    title: 'Animal API'
    description: 'blabla'
    version: '0.1.0'
    path_segment_name_generator: 'api_platform.path_segment_name_generator.dash'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        pagination:
#            items_per_page: 10 # deprecated
    defaults:
        pagination_items_per_page: 10
