api_platform:
    title: 'Animal API'
    description: 'blabla'
    version: '0.1.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
